export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const LOGOUT = 'LOGOUT';


export const USER_ADCLIENTDED = 'USER_ADDED';
export const USER_DESACTIVATED = 'USER_DESACTIVATED';

export const CLIENT_ADDED = 'CLIENT_ADDED';
export const CLIENT_DESACTIVATED = 'CLIENT_DESACTIVATED';

export const CLIENT_ADD_FAIL = 'CLIENT_ADD_FAIL';
export const USER_ADD_FAIL = 'USER_ADD_FAIL';

